import { Metadata } from "next";
import { ReactNode } from "react";
interface PrivateLayoutProps {
    children: ReactNode;
}
export const metadata: Metadata = {
    title: 'Auth ',
    description: 'Generated by create next app',
}
export default async function AuthLayout({ children }: PrivateLayoutProps) {
    return (
        <>
            <div className="flex items-center justify-center h-screen">

                {children}

            </div>
        </>
    )
}
